name: Auto Fetch and Purge Ad Rules

on:
  schedule:
    - cron: '27 04 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Python Script
      run: python update_rules.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        if [ -n "$(git status --porcelain purged_ad_rules.txt)" ]; then
          git add purged_ad_rules.txt
          git commit -m "Auto-update: rules refreshed"
          git push
        else
          echo "No changes detected."
        fi
